/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openbravo.pos.config;

import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.data.gui.MessageInf;
import com.openbravo.data.user.DirtyManager;
import com.openbravo.pos.forms.AppConfig;
import com.openbravo.pos.types.GeneralTypes;
import com.openbravo.pos.util.AltEncrypter;
import com.openbravo.pos.util.FileChooserCert;
import coop.guenoa.afip.util.Configuracion;
import coop.guenoa.afip.wsaa.TicketLogin;
import coop.guenoa.afip.wsaa.Wsaa;
import coop.guenoa.afip.wsaa.WsaaException;
import coop.guenoa.afip.wsfev1.DummyResponse;
import coop.guenoa.afip.wsfev1.Wsfe_v1;
import java.awt.Component;
import java.awt.Toolkit;
import java.rmi.RemoteException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ariel
 */
public class JPanelConfigTPV extends javax.swing.JPanel implements PanelConfig {

    private final DirtyManager dirty = new DirtyManager();
    private final ComboBoxValModel m_CategoryModel;

    /**
     * Creates new form JPanelConfigTPV
     */
    public JPanelConfigTPV() {
        initComponents();

        List a = GeneralTypes.getTypesResponsible();
        m_CategoryModel = new ComboBoxValModel(a);
        m_jCategory.setModel(m_CategoryModel);

        jbtnFileName.addActionListener(new FileChooserCert(m_certificado));

        m_cuit.getDocument().addDocumentListener(dirty);
        m_jCategory.addActionListener(dirty);
        m_puntoventa.getDocument().addDocumentListener(dirty);
        m_cboSalidaFiscal.addActionListener(dirty);
        m_certificado.getDocument().addDocumentListener(dirty);
        m_usuario.getDocument().addDocumentListener(dirty);
        m_password.getDocument().addDocumentListener(dirty);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        m_certificado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        m_cboSalidaFiscal = new javax.swing.JComboBox<>();
        m_puntoventa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        m_cuit = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        m_jCategory = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        m_password = new javax.swing.JPasswordField();
        m_usuario = new javax.swing.JTextField();
        jbtnFileName = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtn_test_wsaa = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("TPV"));

        jLabel1.setText("Cuit");

        jLabel3.setText("Puto de Venta AFIP");

        jLabel5.setText("Validación");

        m_cboSalidaFiscal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NoDefinido", "WSFEv1-HOMO", "WSFEv1", "IMPRESORA-FISCAL" }));

        jLabel6.setText("Certificado");

        jLabel7.setText("Usuario");

        try {
            m_cuit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Tipo de Responsable");

        jLabel8.setText("Contraseña");

        jbtnFileName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/fileopen.png"))); // NOI18N
        jbtnFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFileNameActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Test"));

        jbtn_test_wsaa.setText("Test Wsaa");
        jbtn_test_wsaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_test_wsaaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jbtn_test_wsaa, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtn_test_wsaa)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(m_cuit, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(m_jCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(m_password, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addContainerGap(151, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(m_cboSalidaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m_puntoventa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(m_certificado, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jbtnFileName))
                                .addComponent(m_usuario)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_cuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_jCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_puntoventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(m_cboSalidaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(m_certificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(jbtnFileName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(m_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(m_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFileNameActionPerformed

    }//GEN-LAST:event_jbtnFileNameActionPerformed

    private void jbtn_test_wsaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_test_wsaaActionPerformed

        Wsaa auth = new Wsaa("wsfe");

        TicketLogin ticketLogin = null;
        try {
            ticketLogin = auth.getTicketLogin();
            
            new MessageInf(MessageInf.SGN_SUCCESS, " ", ticketLogin.toString()).show(this);

        } catch (WsaaException e) {
            // TODO Auto-generated catch block
            Toolkit.getDefaultToolkit().beep();
            new MessageInf(MessageInf.SGN_WARNING, e.getMessage()).show(this);

        }

        Wsfe_v1 wsfev1 = new Wsfe_v1();

        DummyResponse response = null;
        try {
            response = wsfev1.FEDummy();
        } catch (RemoteException ex) {
            Logger.getLogger(JPanelConfigTPV.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("App Server: " + response.getAppServer());
        System.out.println("Auth Server: " + response.getAuthServer());
        System.out.println("Db Server: " + response.getDbServer());

    }//GEN-LAST:event_jbtn_test_wsaaActionPerformed

    @Override
    public void loadProperties(AppConfig config) {
        m_cuit.setText(config.getProperty("wsafip.CUIT"));
        m_CategoryModel.setSelectedKey(config.getProperty("wsafip.typeresp"));
        m_puntoventa.setText(config.getProperty("wsafip.puntoventa"));

        m_cboSalidaFiscal.setSelectedItem(config.getProperty("wsafip.salidafiscal"));

        m_certificado.setText(config.getProperty("wsafip.KEYSTORE"));

        String sUser = config.getProperty("wsafip.KEYSTORE_USER");
        String sPassword = config.getProperty("wsafip.KEYSTORE_PASS");
        if (sUser != null && sPassword != null && sPassword.startsWith("crypt:")) {
            // La clave esta encriptada.
            AltEncrypter cypher = new AltEncrypter("cypherkey" + sUser);
            sPassword = cypher.decrypt(sPassword.substring(6));
        }
        m_usuario.setText(sUser);
        m_password.setText(sPassword);

        /*
        Cargamos la configuracion WSAFIP
         */
        Configuracion.CUIT = m_cuit.getText();
        Configuracion.DEBUG = true;
        Configuracion.HOMOLOCION = m_cboSalidaFiscal.getSelectedItem().equals("WSFEv1-HOMO");
        Configuracion.KEYSTORE = m_certificado.getText();
        Configuracion.KEYSTORE_USER = sUser;
        Configuracion.KEYSTORE_PASS = sPassword;

        dirty.setDirty(false);
    }

    @Override
    public void saveProperties(AppConfig config) {

        config.setProperty("wsafip.CUIT", m_cuit.getText());
        config.setProperty("wsafip.typeresp", (String) m_CategoryModel.getSelectedKey());
        config.setProperty("wsafip.puntoventa", m_puntoventa.getText());

        config.setProperty("wsafip.salidafiscal", comboValue(m_cboSalidaFiscal.getSelectedItem()));

        config.setProperty("wsafip.KEYSTORE", m_certificado.getText());
        config.setProperty("wsafip.KEYSTORE_USER", m_usuario.getText());

        AltEncrypter cypher = new AltEncrypter("cypherkey" + m_usuario.getText());
        config.setProperty("wsafip.KEYSTORE_PASS", "crypt:" + cypher.encrypt(new String(m_password.getPassword())));

        config.setProperty("wsafip.HTTP_PROXY", "");
        config.setProperty("wsafip.HTTP_PROXY_PORT", "");
        config.setProperty("wsafip.HTTP_PROXY_USER", "");
        config.setProperty("wsafip.HTTP_PROXY_PASS", "");

        dirty.setDirty(false);
    }

    @Override
    public boolean hasChanged() {
        return dirty.isDirty();
    }

    @Override
    public Component getConfigComponent() {
        return this;
    }

    private String comboValue(Object value) {
        return value == null ? "" : value.toString();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnFileName;
    private javax.swing.JButton jbtn_test_wsaa;
    private javax.swing.JComboBox<String> m_cboSalidaFiscal;
    private javax.swing.JTextField m_certificado;
    private javax.swing.JFormattedTextField m_cuit;
    private javax.swing.JComboBox<String> m_jCategory;
    private javax.swing.JPasswordField m_password;
    private javax.swing.JTextField m_puntoventa;
    private javax.swing.JTextField m_usuario;
    // End of variables declaration//GEN-END:variables
}
